version: '3.8'

services:
 web1:
  build: ./app1
  ports:
  - 8000:5000
  volumes:
  - ./:/app1

 mysqldb:
  image: mysql:8.0-oracle
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: